import '../models/BookModel.dart';

List<BookModel> initialBookData = [
  BookModel(
    id: "1",
    title: "The Laws of Human Nature",
    author: "Robert Greene",
    description:
    "The book explores the psychological motives driving human behavior. Through 18 laws, Robert Greene teaches how to read people's true intentions, master emotions, and avoid manipulation. Using historical examples, he helps readers understand themselves and others to gain social intelligence and influence.",
    rating: "4.7",
    coverUrl:
    "https://i.pinimg.com/1200x/db/8f/16/db8f1654e94d267a5fcbb9ecc4b960cf.jpg",
    bookurl: "placeholder_3.pdf",
    category: "Psychology",
    language: "English",
    createdAt: DateTime.now().toString(),
    pages: 624,
    price: 35,
    isInBasket: false,
    isBookmarked: false,
    isOwned: false,
    isOnSale: false,
  ),

  BookModel(
    id: "15",
    title: "Art & Fear",
    author: "David Bayles and ed Orland",
    description: "Art & Fear explores the way art gets made, the reasons it often doesn't get made, and the nature of the difficulties that cause so many artists to give up along the way. The book's co-authors, David Bayles and Ted Orland, are themselves both working artists, grappling daily with the problems of making art in the real world. Their insights and observations, drawn from personal experience, provide an incisive view into the world of art as it is expeienced by artmakers themselves.",
    rating: "4.6",
    coverUrl:
    "https://m.media-amazon.com/images/I/419WC2xc7HL._UF1000,1000_QL80_.jpg",
    bookurl: "placeholder_3.pdf",
    category: "Art",
    language: "English",
    createdAt: DateTime.now().toString(),
    pages: 122,
    price: 30,
    isInBasket: false,
    isBookmarked: false,
    isOwned: false,
    isOnSale: false,
  ),
  BookModel(
    id: "10",
    title: "The Midnight Library",
    author: "Matt Haig",
    description:
    "Between life and death lies a library where each book represents a different version of your life. Nora Seed must choose which life to live.",
    rating: "4.3",
    coverUrl:
    "https://i.pinimg.com/1200x/57/f3/c8/57f3c8e26f7841e92acba841eec6c9c1.jpg",
    bookurl: "placeholder_7.pdf",
    category: "Fantasy",
    language: "English",
    createdAt: DateTime.now().toString(),
    pages: 304,
    price: 25,
    isInBasket: false,
    isBookmarked: false,
    isOwned: false,
    isOnSale: false,
  ),
  BookModel(
    id: "20",
    title: "Save Me An Orange",
    author: "Hayley Grace",
    description: "In her debut poetry collection, Hayley gives voice to the roots of struggle and pain growing up, as well as the love and pursuit of self-acceptance that were fundamental in her own choice to live. Her verses weave a narrative that is both deeply personal and universally resonant–through shadows of the past and the fleeting moments of joy captured in the simplicity of sharing an orange.",
    rating: "4.7",
    coverUrl:
    "https://i.pinimg.com/736x/26/dd/62/26dd62a92a9332879788ca13fbdad38f.jpg",
    bookurl: "placeholder_3.pdf",
    category: "Poetry",
    language: "English",
    createdAt: DateTime.now().toString(),
    pages: 114,
    price: 35,
    isInBasket: false,
    isBookmarked: false,
    isOwned: false,
    isOnSale: false,
  ),
  BookModel(
    id: "16",
    title: "The Design Of Everyday Things",
    author: "Don Norman",
    description:"ven The Smartest Among Us Can Feel Inept As We Fail To Figure Out Which Light Switch Or Oven Burner To Turn On, Or Whether To Push, Pull, Or Slide A Door. The Fault, Argues This Ingenious,Even Liberating,Book, Lies Not In Ourselves, But In Product Design That Ignores The Needs Of Users And The Principles Of Cognitive Psychology. The Problems Range From Ambiguous And Hidden Controls To Arbitrary Relationships Between Controls And Functions, Coupled With A Lack Of Feedback Or Other Assistance And Unreasonable Demands On Memorization. The Design Of Everyday Things Shows That Good, Usable Design Is Possible. The Rules Are Simple: Make Things Visible, Exploit Natural Relationships That Couple Function And Control, And Make Intelligent Use Of Constraints. The Goal: Guide The User Effortlessly To The Right Action On The Right Control At The Right Time.In This Entertaining And Insightful Analysis, Cognitive Scientist Don Norman Hails Excellence Of Design As The Most Important Key To Regaining The Competitive Edge In Influencing Consumer Behaviour. Now Fully Expanded And Updated, With A New Introduction By The Author, The Design Of Everyday Things Is A Powerful Primer On How,And Why,Some Products Satisfy Customers While Others Only Frustrate Them.",
    rating: "4.6",
    coverUrl:
    "https://i.pinimg.com/736x/ed/0b/da/ed0bda4ac16530a6ac11d8ed3f3c7f28.jpg",
    bookurl: "placeholder_3.pdf",
    category: "Art",
    language: "English",
    createdAt: DateTime.now().toString(),
    pages: 368,
    price: 27,
    isInBasket: false,
    isBookmarked: false,
    isOwned: false,
    isOnSale: false,
  ),
  BookModel(
    id: "17",
    title: "أسرار الفن التشكيلى",
    author: "محمود البسيوني",
    description:"عولجت تلك الأسرار في ثلاث أبواب رئيسية: الأول: يتعرض لتشريح العمل الفني (الخط، المساحة، والملس، واللون، والضوء، والحجم، والكتلة، والفراغ.. إلخ) والثاني: يشرح طبيعة (الموضوع، والمضمون، والإثارة، والتلقائية، والخيال، والتجريد، والإيقاع، والأسلوب، والتعبير، ونقل الخبرة.. إلخ) والثالث: يبين صلة الفن التشكيلي (بالحياة، والصناعة، والتراث، والأخلاق، والدين، والتربية، والعلم، والأدب، والفلسفة، والتحليل النفسي.. على أسس حضارية).",
    rating: "4.6",
    coverUrl:
    "https://www.alarabimag.com/images/thumbs/30221.jpg",
    bookurl: "placeholder_3.pdf",
    category: "Art",
    language: "Arabic",
    createdAt: DateTime.now().toString(),
    pages: 238,
    price: 15,
    isInBasket: false,
    isBookmarked: false,
    isOwned: false,
    isOnSale: false,
  ),

  BookModel(
    id: "2",
    title: "الوحش",
    author: "كارمن مولا",
    description:
    "ليست جائحة الكوليرا الشيء الوحيد الذي يُرعب سكان مدريد في عام 1834، فخارج أسوار المدينة تظهر جثث ممزقة لفتيات صغيرات. تتحدث الشائعات عن «الوحش» الذي يخشاه الجميع، على الرغم من أن أحدًا لم يره فعلًا سواء داخل أسوار العاصمة أو خارجها. حين تختفي الصغيرة كلارا، تنطلــــق أختها لوثيـا في سباق محمــــوم للعثور عليها. يتــــــلاقى طــــريـــــقها مـــــــع الصحفــــي الفضولي دييجو والشرطي الأعور دونوسو، والراهب براوليـــــو. يتعثرون جميعًـــا بشـــيء يقلب حيــاتهــم: خاتم ذهبــــي غــــامض علــــيه مطرقتان متقاطعتان، وهو الغرض الذي لا يمانع البعض أن يَقتل من أجله. ببراعة مذهلة.",
    rating: "4.4",
    coverUrl:
    "https://i.pinimg.com/736x/5b/b0/44/5bb044d5af6a7841619ad83d49a898a1.jpg",
    bookurl: "placeholder_1.pdf",
    category: "Fiction",
    language: "Arabic",
    createdAt: DateTime.now().toString(),
    pages: 496,
    price: 30,
    isInBasket: false,
    isBookmarked: false,
    isOwned: false,
    isOnSale: false,
  ),

  BookModel(
    id: "6",
    title: "Man’s Search for Meaning",
    author: "Viktor E. Frankl",
    description:
    "Written by Holocaust survivor Viktor Frankl, the book explores how finding meaning gives humans the strength to endure suffering. Through his experience in Nazi concentration camps, Frankl develops logotherapy — a philosophy that argues life’s purpose is discovered through resilience, love, and inner freedom.",
    rating: "4.8",
    coverUrl:
    "https://i.pinimg.com/736x/79/1d/0f/791d0f941144faa19c44c9d684d3581a.jpg",
    bookurl: "placeholder_4.pdf",
    category: "Psychology",
    language: "English",
    createdAt: DateTime.now().toString(),
    pages: 200,
    price: 28,
    isInBasket: false,
    isBookmarked: false,
    isOwned: true,
    isOnSale: false,
  ),
  BookModel(
    id: "27",
    title: "آلام فرتر",
    author: "يوهان فون غوتة",
    description:
    "ينمُّ جيتي على نفسه في أولى الرسائل التي كتبها فرتر؛ فإن فرتر الذي يقول لنا في تلك الرسالة: «ما الإنسان؟ وكيف يجرؤ على مؤاخذة نفسه؟» ثم يقول لنا: «أريد أن أنعم بالحاضر وليذهب الماضي حيث ذهب.» إنما هو جيتي بعينه الذي لا يرى الإنسان إلا ألعوبة في يد القدر ولا يطلب من الحياة إلا ما تعطيه حين تعطيه، وكلما تقدمنا في القراءة سطرًا عرفنا جيتي من وراء فرتر وعرفنا أنه هو الذي يتسلى عن المصائب والآلام بقراءة الشعر الإغريقي القديم، فكل مصيبة استطاع أن يحيلها «إلى شعور فني» فهي مصيبة ذاهبة ومحنة مقبولة، وقصة فرتر كلها إنْ هي إلا لوعة أحالها إلى «شعور فني» فاطمأنَّ واستراح.",
    rating: "3.8",
    coverUrl:
    "https://i.pinimg.com/736x/0c/c2/4f/0cc24f2bfce1f40fc864532b06fabd75.jpg",
    bookurl: "placeholder_4.pdf",
    category: "Literature",
    language: "Arabic",
    createdAt: DateTime.now().toString(),
    pages: 239,
    price: 19,
    isInBasket: false,
    isBookmarked: false,
    isOwned: false,
    isOnSale: true,
  ),
  BookModel(
    id: "22",
    title: "حضارة العرب",
    author: "غوستاف لوبون",
    description:
    "يؤرخ لنا هذا الكتاب مجد العرب التَالِدِ الذي يضرب بجذوره في عمق أزمانٍ كان فيها العرب فرسان الحضارة الذين أضاءوا العالم بأمجادهم. ويوضح لنا هذا الكتاب الأقسام التي انقسم إليها العرب، والأمجاد التي حققوها عبر العصور المختلفة، والمبلغ الذي وصلوا إليه في مختلف العلوم والآداب، والفنون، وسياساتهم الحربية، والأدوات التي كانوا يستعينون بها في إدارة رحى الحرب، والنقود التي كانوا يستخدمونها عَبْرَ العصور المختلفة. وقد ذكر الكاتب طَرَفًا من أخلاق العرب وعاداتهم ومكانة المرأة عندهم؛ لِمَا لها من دلالة على رقيِّهم وتقدمهم، وقد برع الكاتب في الكشف عن أوجه هذه الحضارة، فذكر تفوقهم في الزراعة والصناعة والتجارة. ويمكننا أن نصف هذا الكتاب بأنه جاء كاشفًا عن مكنون الحضارة العربية، جامعًا لعلومها، وفنونها، وآدابها.",
    rating: "3.8",
    coverUrl:
    "https://i.pinimg.com/1200x/48/e8/7c/48e87cde6c69c7d5be4cb658521e672f.jpg",
    bookurl: "placeholder_4.pdf",
    category: "History",
    language: "Arabic",
    createdAt: DateTime.now().toString(),
    pages: 666,
    price: 15,
    isInBasket: false,
    isBookmarked: false,
    isOwned: false,
    isOnSale: false,
  ),
  BookModel(
    id: "21",
    title: "A Breath of Life",
    author: "Clarice Lispector",
    description: "A mystical dialogue between a male author (a thinly disguised Clarice Lispector) and his/her creation, a woman named Angela, this posthumous work has never before been translated. Lispector did not even live to see it published.At her death, a mountain of fragments remained to be “structured” by Olga Borelli. These fragments form a dialogue between a god-like author who infuses the breath of life into his creation: the speaking, breathing, dying creation herself, Angela Pralini. The work’s almost occult appeal arises from the perception that if Angela dies, Clarice will have to die as well. And she did.",
    rating: "4.2",
    coverUrl:
    "https://i.pinimg.com/736x/f4/26/45/f42645d2737951af30390bbdb9374835.jpg",
    bookurl: "placeholder_3.pdf",
    category: "Poetry",
    language: "English",
    createdAt: DateTime.now().toString(),
    pages: 167,
    price: 50,
    isInBasket: false,
    isBookmarked: false,
    isOwned: false,
    isOnSale: false,
  ),
  BookModel(
    id: "24",
    title: "Raising Hare: A Memoir",
    author: "Chloe Dalton",
    description:
    "A moving and fascinating meditation on freedom, trust, loss, and our relationship with the natural world, explored through the story of one woman’s unlikely friendship with a wild hare.Imagine you could hold a baby hare and bottle-feed it. Imagine that it lived under your roof and lolloped around your bedroom at night, drumming on the duvet cover when it wanted your attention. Imagine that, over two years later, it still ran in from the fields when you called it and slept in your house for hours on end and gave birth to leverets in your study. For political advisor and speechwriter Chloe Dalton, who spent lockdown deep in the English countryside, far away from her usual busy London life, this became her unexpected reality.",
    rating: "4.3",
    coverUrl:
    "https://i.pinimg.com/1200x/2a/82/a5/2a82a5b7b81ee85f11cdd0d36bc8506d.jpg",
    bookurl: "placeholder_4.pdf",
    category: "Biography",
    language: "English",
    createdAt: DateTime.now().toString(),
    pages: 285,
    price: 25,
    isInBasket: false,
    isBookmarked: false,
    isOwned: false,
    isOnSale: true,
  ),
  BookModel(
    id: "7",
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    description:
    "A young man, Dorian Gray, remains eternally youthful while a portrait of him ages and reveals his moral decay. As he pursues pleasure and vanity, the painting becomes a haunting reflection of his corrupted soul. Wilde’s classic novel examines beauty, sin, and the cost of a life devoted to desire.",
    rating: "4.6",
    coverUrl:
    "https://i.pinimg.com/736x/47/9b/9f/479b9fb3af662656dcec039de3c46486.jpg",
    bookurl: "placeholder_5.pdf",
    category: "Fiction",
    language: "English",
    createdAt: DateTime.now().toString(),
    pages: 254,
    price: 26,
    isInBasket: false,
    isBookmarked: false,
    isOwned: false,
    isOnSale: false,
  ),
  BookModel(
    id: "9",
    title: "What You Are Looking For Is in the Library",
    author: "Michiko Aoyama",
    description:
    "relates five loosely connected stories of five different people who visit a community library in Tokyo, only to find themselves changing for the better, all because of an unexpected book recommendation by the enigmatic librarian. There’s a retail worker who feels her life is stagnating, a woman recently back from maternity leave grappling with her demotion, and several others—all who find new directions and new passion for life, all thanks to the library.",
    rating: "4.6",
    coverUrl:
    "https://i.pinimg.com/1200x/b6/0b/03/b60b037871f3242370c276013733df3c.jpg",
    bookurl: "placeholder_6.pdf",
    category: "Literature",
    language: "English",
    createdAt: DateTime.now().toString(),
    pages: 265,
    price: 40,
    isInBasket: false,
    isBookmarked: false,
    isOwned: false,
    isOnSale: false,
  ),
  BookModel(
    id: "26",
    title: "Will in the World",
    author: "Stephen Greenblatt",
    description:
    "Will in the World interweaves a searching account of Elizabethan England with a vivid narrative of the playwright's life. We see Shakespeare learning his craft, starting a family, and forging a career for himself in the wildly competitive London theater world, while at the same time grappling with dangerous religious and political forces that took less-agile figures to the scaffold. Above all, we never lose sight of the great works―A Midsummer Night's Dream, Romeo and Juliet, Hamlet, Macbeth, and more―that continue after four hundred years to delight and haunt audiences everywhere. The basic biographical facts of Shakespeare's life have been known for over a century, but now Stephen Greenblatt shows how this particular life history gave rise to the world's greatest writer. Bringing together little-known historical facts and little-noticed elements of Shakespeare's plays, Greenblatt makes inspired connections between the life and the works and deliver a dazzling and subtle biography (Richard Lacayo, Time). Readers will experience Shakespeare's vital plays again as if for the first time, but with greater understanding and appreciation of their extraordinary depth and humanity.",
    rating: "4.5",
    coverUrl:
    "https://i.pinimg.com/736x/8a/3d/18/8a3d18b5909b7dd2bcec3d8ad1ea327e.jpg",
    bookurl: "placeholder_4.pdf",
    category: "Biography",
    language: "English",
    createdAt: DateTime.now().toString(),
    pages: 386,
    price: 17,
    isInBasket: false,
    isBookmarked: false,
    isOwned: false,
    isOnSale: false,
  ),

  BookModel(
    id: "27",
    title: "اليرموك بقيادة خالد بن الوليد",
    author: "شوقي ابو خليل",
    description:
    " تفاصيل معركة اليرموك الحاسمة من منظور إسلامي، ويركز على عبقرية خالد بن الوليد القيادية وكيفية توظيفه لتكتيكات عسكرية مبتكرة لصناعة النصر. يتناول الكتاب الترتيبات العسكرية التي قام بها خالد، واستخدامه لسلاح الفرسان المتحرك لمباغتة الروم، بالإضافة إلى غرس روح العزيمة والإيمان في قلوب الجنود المسلمين.",
    rating: "4.6",
    coverUrl:
    "https://i.pinimg.com/736x/fe/7b/30/fe7b30110c82fd370b038488bfc9c14f.jpg",
    bookurl: "placeholder_4.pdf",
    category: "History",
    language: "Arabic",
    createdAt: DateTime.now().toString(),
    pages: 97,
    price: 15,
    isInBasket: false,
    isBookmarked: false,
    isOwned: false,
    isOnSale: false,
  ),

  BookModel(
    id: "11",
    title: "Little Women",
    author: "Louisa May Alcott",
    description:
    "The story of the March sisters as they navigate love, loss, and personal growth during the American Civil War era.",
    rating: "4.5",
    coverUrl:
    "https://i.pinimg.com/1200x/73/81/ec/7381ec6129fa0a06e4239532bf17d9b7.jpg",
    bookurl: "placeholder_6.pdf",
    category: "Classic",
    language: "English",
    createdAt: DateTime.now().toString(),
    pages: 449,
    price: 25,
    isInBasket: false,
    isBookmarked: false,
    isOwned: true,
    isOnSale: false,
  ),
  BookModel(
    id: "23",
    title: "A History of Britain in Ten Enemies",
    author: "Terry Deary",
    description:
    "Ah, Britain. So special. The greatest nation on earth, some say. And we did it all on our own. Didn’t we?Well, as it happens Britannia got its name from the Romans, and for the past two centuries we have been ruled by Germans. But then, as Horrible Histories author Terry Deary argues, nations and their leaders are defined by the enemies they make.The surprisingly sadistic Boudica would be forgotten if it weren't for the Ninth Legion, Elizabeth I a minor royal without the Spanish Armada, and Churchill an opposition windbag without the Nazis. Britain loves its heroes so much we have been known to pickle them in brandy to keep them fresh. And after all, every nation sometimes needs a bit of unifying Blitz spirit (although in an ideal world, we wouldn’t have accidentally let Corporal Hitler go in the first place).",
    rating: "3.8",
    coverUrl:
    "https://i.pinimg.com/1200x/72/72/5e/72725eea33abf55e039feb0378a834a7.jpg",
    bookurl: "placeholder_4.pdf",
    category: "History",
    language: "English",
    createdAt: DateTime.now().toString(),
    pages: 265,
    price: 25,
    isInBasket: false,
    isBookmarked: false,
    isOwned: false,
    isOnSale: false,
  ),
  BookModel(
    id: "25",
    title: "رحلة ابن بطوطة",
    author: "محمد بن عبد الله ابن بطوطة وابن جزي الكلبي",
    description:
    "يُعَدُّ هذا الكتابُ من أشهرِ كُتبِ الرِّحلاتِ في التاريخ؛ فقد عُرِفَ «ابن بطوطة» بكثرةِ أَسْفاره، وبسببِ شُهرتِه العالميةِ لقَّبَته «جمعيةُ كامبريدج» ﺑ «أمير الرحَّالةِ المُسلمِين». بدأَ «ابن بطوطة» رِحلتَه من «طنجة» مَسقطِ رأسِه؛ ناويًا حجَّ بيتِ اللهِ الحرام، ورحَلَ دونَ رفيقٍ ولا قَرِيب، واتخذَ في كلِّ مدينةٍ وقَفَ فيها صاحبًا، فحكى عنه وعن المدينةِ التي قابَلَه فيها. قُدِّرَ زمنُ رِحلاتِه بما يَقربُ من الثلاثينَ عامًا، وقد أَمْلى على «ابن جزي الكلبي» تَفاصيلَ تلكَ الرِّحلاتِ ونَوادرَها، وبعدَما انتهى منَ التدوينِ أطلَقَ على مؤلَّفِه هذا اسمَ: «تُحْفة النُّظَّارِ في غرائبِ الأَمْصارِ وعجائبِ الأَسْفار». لم يَكْتفِ «ابن بطوطة» بالوصفِ الخارجيِّ للأماكنِ التي زارَها، بل استفاضَ في الحديثِ عن مَداخلِ المدنِ ومَخارِجِها وطَبائعِ الشعوبِ المُختلِفةِ التي عاشَرَها، وسرَدَ العديدَ منَ الحِكاياتِ المشوِّقةِ التي جعَلَتْه من رُوَّادِ أدبِ الرحلاتِ في الأدبِ العربي، حتى إنَّنا لا نَستطيعُ الإشارةَ إلى شخصٍ كثيرِ التَّرْحالِ دونَ أن نلقِّبَه ﺑ «ابن بطوطة».",
    rating: "4.0",
    coverUrl:
    "https://i.pinimg.com/736x/14/74/2e/14742e89efeecdb4102599c4c465fb86.jpg",
    bookurl: "placeholder_4.pdf",
    category: "Biography",
    language: "Arabic",
    createdAt: DateTime.now().toString(),
    pages: 687,
    price: 15,
    isInBasket: false,
    isBookmarked: false,
    isOwned: true,
    isOnSale: false,
  ),
  BookModel(
    id: "4",
    title: "كافكا على الشاطئ",
    author: "هاروكي موراكامي",
    description:
    "تحكي الرواية حكايتين متوازيتين: الأولى عن كافكا تامورا، فتى يهرب من منزل أبيه بسبب نبوءة مظلمة، والثانية عن ناكاتا، رجل عجوز فقد ذاكرته ويستطيع التحدث مع القطط. تتقاطع القصتان في عالم يمزج بين الواقع والخيال، حيث يبحث الأبطال عن ذواتهم ومعنى القدر والحب والحرية.",
    rating: "4.6",
    coverUrl:
    "https://i.pinimg.com/736x/32/30/47/32304772b1a4c68be65f05e71b95b9ce.jpg",
    bookurl: "placeholder_3.pdf",
    category: "Literature",
    language: "Arabic",
    createdAt: DateTime.now().toString(),
    pages: 615,
    price: 26,
    isInBasket: false,
    isBookmarked: false,
    isOwned: false,
    isOnSale: false,
  ),
  BookModel(
    id: "19",
    title: "الشاعر",
    author: "مصطفى لطفي المنفلوطي",
    description:"م يكن الحب عند «سيرانو دي بيرجراك» مجرد كلمة جوفاء أو ابتسامة باردة، بل هو التضحية في أسمى صورها. فبينما كان يُحبُّ ابنة عمه «روكسان»، إلا أنه ظن أن أنْفَه الكبيرة تمنع «روكسان» من أن تُبَادلهُ الحُبَّ؛ لذا لم يصارحها بحُبِّهِ، وظل يكتمه في فؤاده، وضَحى بأغلى شيء في حياته من أجل إسعادها، ولم يَعدم الحيلة في أن يزوجها من «كرستيان» الذي اختارته حبيبًا، وظنت أنه أذكى وأشجع إنسان بفضل حيلة «سيرانو»، بل واتخذه «سيرانو» صديقًا مقربًا. ولم تعلم «روكسان» بما في قلب «سيرانو» إلا وهو على فراش الموت. وأراد «المنفلوطي» من روايته أن يوجه رسالة إلى المحبين، مفادها أن الحب هو الفناء من أجل الآخر، والشقاء من أجله، والعطاء بلا مقابل، فقط لمجرد أن تراه سعيدًا، وإن كنت شقيًّا.",
    rating: "4.0",
    coverUrl:
    "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1587593146i/53246494.jpg",
    bookurl: "placeholder_3.pdf",
    category: "Poetry",
    language: "Arabic",
    createdAt: DateTime.now().toString(),
    pages: 179,
    price: 12,
    isInBasket: false,
    isBookmarked: true,
    isOwned: false,
    isOnSale: false,
  ),
  BookModel(
    id: "13",
    title: "The Alchemist",
    author: "Paulo Coelho",
    description:
    "The journey of a shepherd named Santiago who dreams of finding treasure in Egypt, learning profound lessons about destiny and purpose.",
    rating: "4.6",
    coverUrl:
    "https://i.pinimg.com/1200x/2f/21/9b/2f219ba8a4a999a76a60eecbc8eb9372.jpg",
    bookurl: "placeholder_5.pdf",
    category: "Fiction",
    language: "English",
    createdAt: DateTime.now().toString(),
    pages: 208,
    price: 20,
    isInBasket: false,
    isBookmarked: false,
    isOwned: false,
    isOnSale: false,
  ),
  BookModel(
    id: "14",
    title: "The Song of Achilles",
    author: "Madeline Miller",
    description:
    " Patroclus is an awkward young prince, exiled from his homeland after an act of shocking violence. Brought together by chance, they forge an inseparable bond, despite risking the gods' wrath. They are trained by the centaur Chiron in the arts of war and medicine, but when word comes that Helen of Sparta has been kidnapped, all the heroes of Greece are called upon to lay siege to Troy in her name. Seduced by the promise of a glorious destiny, Achilles joins their cause, and torn between love and fear for his friend, Patroclus follows. Little do they know that the cruel Fates will test them both as never before and demand a terrible sacrifice.",
    rating: "4.4",
    coverUrl:
    "https://i.pinimg.com/736x/35/0b/29/350b29b24856ef5d4b3d1b4e01dcf2bf.jpg",
    bookurl: "placeholder_12.pdf",
    category: "Fiction",
    language: "English",
    createdAt: DateTime.now().toString(),
    pages: 408,
    price: 35,
    isInBasket: false,
    isBookmarked: true,
    isOwned: true,
    isOnSale: false,
  ),
  BookModel(
    id: "12",
    title: "عائد إلى حيفا",
    author: "غسان كنفاني",
    description:
    "قصة عائلة فلسطينية تعود إلى مدينتها بعد عشرين عامًا من النكبة لتكتشف ابنها الذي تركته صغيرًا أصبح جنديًا في جيش الاحتلال.",
    rating: "4.7",
    coverUrl:
    "https://i.pinimg.com/736x/90/22/f1/9022f1624ea883852f07c013ff3e5c47.jpg",
    bookurl: "placeholder_9.pdf",
    category: "رواية",
    language: "Arabic",
    createdAt: DateTime.now().toString(),
    pages: 96,
    price: 16,
    isInBasket: false,
    isBookmarked: false,
    isOwned: true,
    isOnSale: false,
  ),
  BookModel(
    id: "5",
    title: "No Longer Human",
    author: "Osamu Dazai",
    description:
    "Told through the notebooks of Oba Yozo, the story portrays a man who feels completely alienated from society. Despite his outward charm and humor, he suffers from deep loneliness and self-loathing. His descent into addiction and despair reveals a painful exploration of identity, shame, and the loss of humanity. "
        "The smile is nothing more than a puckering of ugly wrinkles.",
    rating: "4.75",
    coverUrl:
    "https://i.pinimg.com/736x/8e/ab/d6/8eabd68b9ac3d6eb629a5bc07b6a485b.jpg",
    bookurl: "placeholder_1.pdf",
    category: "Literature",
    language: "English",
    createdAt: DateTime.now().toString(),
    pages: 271,
    price: 25,
    isInBasket: false,
    isBookmarked: false,
    isOwned: false,
    isOnSale: true,
  ),

  BookModel(
    id: "8",
    title: "رجال في الشمس",
    author: "غسان كنفاني",
    description:
    "تحكي الرواية قصة ثلاثة فلسطينيين يحاولون التسلل إلى الكويت بحثًا عن حياة أفضل بعد النكبة. تجمعهم رحلة قاسية في شاحنة صهريج تحت حرارة الصحراء، وتنتهي بمأساة ترمز إلى ضياع جيل كامل.",
    rating: "4.5",
    coverUrl:
    "https://i.pinimg.com/736x/ae/c5/62/aec5626e5a0fad4409dfd0ab751475bc.jpg",
    bookurl: "placeholder_6.pdf",
    category: "Literature",
    language: "Arabic",
    createdAt: DateTime.now().toString(),
    pages: 110,
    price: 20,
    isInBasket: false,
    isBookmarked: false,
    isOwned: false,
    isOnSale: false,
  ),
  BookModel(
    id: "3",
    title: "The Bell Jar",
    author: "Sylvia Plath",
    description:
    "The novel follows Esther Greenwood, a bright young woman who wins a writing internship in New York but feels trapped by societal expectations. As her mental health deteriorates, she spirals into depression and confinement in a mental institution. The story captures the suffocating pressures faced by women and the search for identity and freedom.",
    rating: "4.0",
    coverUrl:
    "https://i.pinimg.com/1200x/1b/ae/22/1bae226df7df268d2ccb699ef134a811.jpg",
    bookurl: "placeholder_2.pdf",
    category: "Fiction",
    language: "English",
    createdAt: DateTime.now().toString(),
    pages: 294,
    price: 25,
    isInBasket: false,
    isBookmarked: false,
    isOwned: false,
    isOnSale: false,
  ),
];